[package]
name = "algs4-searching"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Searching algorithms and symbol tables from Algorithms 4th Edition"

[dependencies]
algs4-fundamentals = { version = "0.1.0", path = "../fundamentals" }

[dev-dependencies]
