[package]
name = "algs4-advanced"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Advanced algorithms from Algorithms 4th Edition"

[dependencies]
algs4-fundamentals = { version = "0.1.0", path = "../fundamentals" }
algs4-searching = { version = "0.1.0", path = "../searching" }
algs4-graphs = { version = "0.1.0", path = "../graphs" }

[dev-dependencies]
