[package]
name = "algs4-fundamentals"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Fundamental data structures and utilities from Algorithms 4th Edition"

[dependencies]
rand = { workspace = true }
rand_distr = "0.4"
lazy_static = "1.5"
byteorder = { workspace = true }

[dev-dependencies]
