[package]
name = "algs4-graphs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Graph algorithms from Algorithms 4th Edition"

[dependencies]
algs4-fundamentals = { version = "0.1.0", path = "../fundamentals" }
algs4-searching = { version = "0.1.0", path = "../searching" }
rand.workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "graph_benchmarks"
harness = false
