[package]
name = "algs4-plotting"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Plotting and visualization library for Algorithms 4th Edition"

[dependencies]
minifb = "0.24"
tiny-skia = "0.11"
lazy_static = "1.4"
